package io.github.numq.haskcore.service.text.syntax

enum class SyntaxTokenType {
    VARIABLE, VARIABLE_PARAMETER, VARIABLE_FIELD, VARIABLE_ID, FUNCTION, FUNCTION_CALL, FUNCTION_INFIX, TYPE, TYPE_VARIABLE, CONSTRUCTOR, MODULE, KEYWORD, KEYWORD_IMPORT, KEYWORD_CONDITIONAL, KEYWORD_REPEAT, KEYWORD_DIRECTIVE, KEYWORD_EXCEPTION, KEYWORD_DEBUG, STRING, STRING_ESCAPE, NUMBER, NUMBER_FLOAT, CHARACTER, BOOLEAN, OPERATOR, PUNCTUATION_BRACKET, PUNCTUATION_DELIMITER, COMMENT, COMMENT_DOCUMENTATION, QUASI_QUOTE, DEFAULT
}