package io.github.numq.haskcore.feature.editor.core.highlighting

enum class HighlightingType {
    KEYWORD, KEYWORD_CONDITIONAL, KEYWORD_IMPORT, KEYWORD_REPEAT, KEYWORD_DIRECTIVE, KEYWORD_EXCEPTION, KEYWORD_DEBUG, TYPE, CONSTRUCTOR, BOOLEAN, FUNCTION, FUNCTION_CALL, VARIABLE, VARIABLE_PARAMETER, VARIABLE_MEMBER, OPERATOR, NUMBER, NUMBER_FLOAT, STRING, CHARACTER, STRING_SPECIAL_SYMBOL, COMMENT, COMMENT_DOCUMENTATION, PUNCTUATION_BRACKET, PUNCTUATION_DELIMITER, MODULE, SPELL, WILDCARD, LOCAL_DEFINITION, LOCAL_REFERENCE, UNKNOWN
}